version: '3.7'
services:
  sql-server-db:
    container_name: sql-server-desafio
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "teste123@"
      ACCEPT_EULA: "Y"